export const SERVICES = [
  {
    slug: 'dunnage',
    icon: '📦',
    name: 'Dunnage Items Supply',
    short: 'Kraft papers, nylon sheets, styrofoam & wooden supports',
    items: ['Kraft Papers', 'Nylon/Plastic Sheets', 'Styrofoam Sheets', 'Adhesive Plaster', 'Wooden Supports'],
    desc: 'High-quality dunnage materials to protect cargo during transit. We supply all types of dunnage items across all Indian ports with fast turnaround.',
  },
  {
    slug: 'provisions',
    icon: '🍖',
    name: 'Provisions',
    short: 'Fresh, dry & frozen — meats, seafood, dairy, groceries',
    items: ['Meats Fresh/Frozen', 'Seafood', 'Poultry', 'Dairy Products', 'Fruit & Vegetables', 'General Groceries', 'Asian Goods & Spices', 'Beverages & Juices', 'Gourmet Foods', 'Dry Goods', 'Confectionery', 'Flowers'],
    desc: 'Complete provisions supply for vessels of all types. Our warehouse facilities include chillers, freezers, and professional packaging to maintain freshness.',
  },
  {
    slug: 'deck-engine-stores',
    icon: '⚙️',
    name: 'Deck & Engine Stores',
    short: 'Full ISSA catalogue — tools, ropes, valves, safety gear',
    items: ['Tools & Hardware', 'Hoses & Ropes', 'Hawsers & Lashing Equipment', 'Wire & Fasteners', 'Valves & Pipes', 'Safety Gear', 'Cargo Nets', 'Pilot Ladders', 'Grinding Wheels', 'Seals & Bearings', 'Distilled Water', 'Lifting Equipment'],
    desc: 'Comprehensive deck and engine stores from the full ISSA catalogue. All items sourced from certified suppliers and delivered directly to your vessel.',
  },
  {
    slug: 'bonded-stores',
    icon: '🍺',
    name: 'Bonded Stores',
    short: 'Beer, cigarettes, wine, tobacco & laboratory alcohol',
    items: ['Beer (Domestic & Imported)', 'Cigarettes & Cigars', 'Wine (Imported/Australian)', 'Laboratory Alcohol', 'Cask Wine', 'Low Alcohol Beer', 'Tobacco Products'],
    desc: 'Licensed bonded stores supply with full customs documentation. All items supplied with proper port authority clearance and documentation.',
  },
  {
    slug: 'lsa-ffa',
    icon: '🦺',
    name: 'Life Saving Equipment',
    short: 'SOLAS compliant — lifejackets, life-rafts, EPIRBs, flares',
    items: ['Lifejackets', 'Immersion Suits', 'Rescue Boats', 'Life-rafts & Servicing', 'Line Throwers', 'Air Horns', 'Lifebuoy Lights', 'Hydrostatic Release Units', 'Life-rings', 'Flares', 'SARTs', 'EPIRBs'],
    desc: 'SOLAS & MARPOL compliant life saving and fire fighting equipment. All items certified and supplied with proper documentation for port state control.',
  },
  {
    slug: 'electrical-stores',
    icon: '⚡',
    name: 'Electrical Stores',
    short: 'Lamps, batteries, cables, motors & domestic appliances',
    items: ['Lamps & Lighting', 'Batteries', 'Cable & Accessories', 'Switches & Relays', 'Fuses', 'Fans & Motors', 'Heating Elements', 'Watertight Fittings', 'Domestic Appliances', 'Torches', 'Antenna Accessories'],
    desc: 'Complete electrical stores for marine applications. All electrical items are marine-grade and compliant with international maritime standards.',
  },
  {
    slug: 'electronics-charts',
    icon: '📡',
    name: 'Electronics & Charts',
    short: 'Radars, GPS, GMDSS, VHF radios & Admiralty charts',
    items: ['Radars & Depth Sounders', 'GPS & Plotters', 'VHF/UHF Radios', 'GMDSS Equipment', 'EPIRBs & SARTs', 'British Admiralty Charts', 'Nautical Publications', 'Sextants', 'Log Books', 'Code Flags'],
    desc: 'Navigation electronics and chart supply from leading manufacturers. British Admiralty Charts and nautical publications always in stock.',
  },
  {
    slug: 'marine-flags',
    icon: '🚩',
    name: 'Marine Flags',
    short: 'Ensigns of all countries, pennants — worldwide courier',
    items: ['National Ensigns (All Countries)', 'Courtesy Flags', 'Alphabet Pennants', 'Numeral Pennants', 'Answering Pennants', 'Signal Flags'],
    desc: 'Complete range of marine flags for all nations. Worldwide courier dispatch available. Custom flag orders accepted with fast turnaround.',
  },
  {
    slug: 'marine-chemicals',
    icon: '🧪',
    name: 'Marine Chemicals',
    short: 'Wilhelmsen, DEB, Marinol — water treatment & cleaning',
    items: ['Wilhelmsen Products', 'DEB Products', 'Marinol', 'Rustoff Rust Removers', 'AFFF Fire Suppressants', 'Water Treatment Chemicals', 'Fuel Oil Treatment', 'Cleaning Chemicals', 'Test Kits'],
    desc: 'Marine chemicals in 25L, 208L, and 1000L IBC containers. Authorized stockist for Wilhelmsen, DEB, and Marinol product lines.',
  },
  {
    slug: 'marine-oils',
    icon: '🛢️',
    name: 'Marine Oils & Lubricants',
    short: 'Castrol authorized stockist — fuel oils, lubes, greases',
    items: ['Fuel Oils', 'Lubricating Oils', 'Greases', 'Stern Tube Greases', 'Hydraulic Oils', 'All Major Brands'],
    desc: 'Authorized Castrol Oil stockist. Full range of marine lubricants, greases, and fuel oils. All major brands available with competitive pricing.',
  },
  {
    slug: 'marine-paints',
    icon: '🎨',
    name: 'Marine Paints & Coatings',
    short: 'International Paint, Jotun, Hempel, Sigma, Blakes',
    items: ['International Paint', 'Jotun Paints', 'Hempel Coatings', 'Sigma Paints', 'Blakes Marine', 'Antifouling Coatings', 'Marine Varnishes'],
    desc: 'Premium marine paints and coatings from the world\'s leading manufacturers. Antifouling, topcoats, primers, and specialty coatings always in stock.',
  },
  {
    slug: 'ship-repair',
    icon: '🔧',
    name: 'Ship Repair & Fabrication',
    short: 'MIG/TIG/MMA welding, engine repairs, underwater services',
    items: ['MIG/TIG/MMA Welding', 'Engine & Boiler Repairs', 'Pipe Replacement', 'AC System Repair', 'Motor Rewinding', 'Hatch Cover Repairs', 'Steering & Rudder Gear', 'Hydraulic Grab Overhauling', 'Radio & Navigation Equipment', 'Underwater Welding/Cutting', 'Hull Cleaning', 'ROV Services'],
    desc: 'Full-service ship repair and fabrication. Our certified engineers handle everything from minor repairs to major overhauls. Underwater services with class-certified divers.',
  },
]

export const PORTS = [
  { name: 'Kakinada', state: 'Andhra Pradesh', home: true, x: 62, y: 58 },
  { name: 'Visakhapatnam', state: 'Andhra Pradesh', home: false, x: 60, y: 52 },
  { name: 'Chennai', state: 'Tamil Nadu', home: false, x: 58, y: 68 },
  { name: 'Kochi', state: 'Kerala', home: false, x: 48, y: 76 },
  { name: 'Mumbai', state: 'Maharashtra', home: false, x: 32, y: 52 },
  { name: 'Kandla', state: 'Gujarat', home: false, x: 22, y: 38 },
  { name: 'Kolkata', state: 'West Bengal', home: false, x: 72, y: 42 },
  { name: 'Paradip', state: 'Odisha', home: false, x: 68, y: 48 },
  { name: 'Haldia', state: 'West Bengal', home: false, x: 70, y: 44 },
  { name: 'Mangalore', state: 'Karnataka', home: false, x: 42, y: 66 },
  { name: 'Tuticorin', state: 'Tamil Nadu', home: false, x: 54, y: 80 },
  { name: 'Ennore', state: 'Tamil Nadu', home: false, x: 59, y: 67 },
  { name: 'Gangavaram', state: 'Andhra Pradesh', home: false, x: 61, y: 54 },
]

export const STATS = [
  { value: '18+', label: 'Years in Operation' },
  { value: 'ALL', label: 'Indian Ports Covered' },
  { value: '24×7', label: 'Service Availability' },
  { value: 'ISO 9001', label: 'Quality Certified' },
  { value: '500+', label: 'Vessels Served' },
  { value: '12+', label: 'Service Categories' },
]
